/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: broker.proto */

#ifndef PROTOBUF_C_broker_2eproto__INCLUDED
#define PROTOBUF_C_broker_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Broker__MessageHeader Broker__MessageHeader;
typedef struct _Broker__ClientInfo Broker__ClientInfo;
typedef struct _Broker__SystemStats Broker__SystemStats;


/* --- enums --- */


/* --- messages --- */

/*
 * Routing envelope, carried as its own ZMQ frame ahead of an opaque payload
 * frame. The broker parses only this header to route a message and never looks
 * at the payload that follows, so any payload encoding (a packed protobuf Any,
 * JSON, raw bytes) passes through untouched - see common/wireframe.h.
 */
struct  _Broker__MessageHeader
{
  ProtobufCMessage base;
  char *handler_key;
  char *sender_id;
  char *topic;
  char *origin_broker_id;
  /*
   * 16 raw UUID bytes (see generateBinaryUUID). `bytes` and `string` share a
   * wire type, so peers still speaking 36-char text uuids stay parseable -
   * the dedup treats both as opaque.
   */
  ProtobufCBinaryData message_uuid;
  char *reply_topic;
};
#define BROKER__MESSAGE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&broker__message_header__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _Broker__ClientInfo
{
  ProtobufCMessage base;
  char *id;
  size_t n_subscriptions;
  char **subscriptions;
  /*
   * Messages the broker tried to deliver to this client but had to drop
   * (full pipe or unroutable), since the client connected. A growing value
   * means the client is not keeping up.
   */
  uint64_t dropped_messages;
};
#define BROKER__CLIENT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&broker__client_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL, 0 }


struct  _Broker__SystemStats
{
  ProtobufCMessage base;
  char *broker_id;
  int32_t clients_count;
  int32_t peers_count;
  int32_t msgs_per_sec;
  double kb_per_sec;
  int64_t total_msgs;
  int64_t uptime_sec;
  size_t n_connected_clients;
  Broker__ClientInfo **connected_clients;
  /*
   * Discovery cluster this broker currently meshes in; empty when discovery
   * is disabled. Changes at runtime via a SET_CLUSTER message.
   */
  char *cluster;
  /*
   * Deliveries dropped across all clients since the broker started.
   */
  uint64_t total_dropped;
};
#define BROKER__SYSTEM_STATS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&broker__system_stats__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0,NULL, (char *)protobuf_c_empty_string, 0 }


/* Broker__MessageHeader methods */
void   broker__message_header__init
                     (Broker__MessageHeader         *message);
size_t broker__message_header__get_packed_size
                     (const Broker__MessageHeader   *message);
size_t broker__message_header__pack
                     (const Broker__MessageHeader   *message,
                      uint8_t             *out);
size_t broker__message_header__pack_to_buffer
                     (const Broker__MessageHeader   *message,
                      ProtobufCBuffer     *buffer);
Broker__MessageHeader *
       broker__message_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   broker__message_header__free_unpacked
                     (Broker__MessageHeader *message,
                      ProtobufCAllocator *allocator);
/* Broker__ClientInfo methods */
void   broker__client_info__init
                     (Broker__ClientInfo         *message);
size_t broker__client_info__get_packed_size
                     (const Broker__ClientInfo   *message);
size_t broker__client_info__pack
                     (const Broker__ClientInfo   *message,
                      uint8_t             *out);
size_t broker__client_info__pack_to_buffer
                     (const Broker__ClientInfo   *message,
                      ProtobufCBuffer     *buffer);
Broker__ClientInfo *
       broker__client_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   broker__client_info__free_unpacked
                     (Broker__ClientInfo *message,
                      ProtobufCAllocator *allocator);
/* Broker__SystemStats methods */
void   broker__system_stats__init
                     (Broker__SystemStats         *message);
size_t broker__system_stats__get_packed_size
                     (const Broker__SystemStats   *message);
size_t broker__system_stats__pack
                     (const Broker__SystemStats   *message,
                      uint8_t             *out);
size_t broker__system_stats__pack_to_buffer
                     (const Broker__SystemStats   *message,
                      ProtobufCBuffer     *buffer);
Broker__SystemStats *
       broker__system_stats__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   broker__system_stats__free_unpacked
                     (Broker__SystemStats *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Broker__MessageHeader_Closure)
                 (const Broker__MessageHeader *message,
                  void *closure_data);
typedef void (*Broker__ClientInfo_Closure)
                 (const Broker__ClientInfo *message,
                  void *closure_data);
typedef void (*Broker__SystemStats_Closure)
                 (const Broker__SystemStats *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor broker__message_header__descriptor;
extern const ProtobufCMessageDescriptor broker__client_info__descriptor;
extern const ProtobufCMessageDescriptor broker__system_stats__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_broker_2eproto__INCLUDED */
